drive a = "."
drive b = "."
drive c = "."
drive d = "."
drive e = "."
drive f = "."
drive g = "."
drive h = "."
drive i = "."
drive j = "."
drive k = "."
drive l = "."
drive m = "."
drive n = "."
drive o = "."
drive p = "."
